Add path check

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -5,7 +5,13 @@ set -u
 
 main() {
     echo '--- Running scan'
-    echo $(which kubescape)
+    if ! [ -x "$(command -v kubescape)" ]; then
+        echo 'Error: kubescape is not installed.' >&2
+        exit 1
+    fi
+
+    echo "$BUILDKITE_PLUGIN_KUBESCAPE_DIRECTORY"
+    echo "$BUILDKITE_PLUGIN_KUBESCAPE_FRAMEWORK"
 }
 
 main
